name: awesome_lints
description: Comprehensive custom lint rules for Dart and Flutter.
version: 1.0.0
homepage: https://github.com/LucasXu0/awesome_lints
repository: https://github.com/LucasXu0/awesome_lints
issue_tracker: https://github.com/LucasXu0/awesome_lints/issues

environment:
  sdk: ^3.10.0

dependencies:
  analyzer: ^8.4.0
  analyzer_plugin: ^0.13.10
  custom_lint_builder: ^0.8.1
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
