name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint and Analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter with FVM
        uses: kuhnroyal/flutter-fvm-config-action@v3
        with:
          path: '.fvmrc'

      - name: Install FVM
        run: |
          dart pub global activate fvm
          fvm install

      - name: Install dependencies
        run: fvm dart pub get

      - name: Check dart format in lib
        run: fvm dart format --set-exit-if-changed lib

      - name: Run dart analyze in lib
        run: fvm dart analyze lib

      - name: Check dart format in test
        run: fvm dart format --set-exit-if-changed test

      - name: Run dart analyze in test
        run: fvm dart analyze test

      - name: Run custom_lint in test
        run: fvm dart run custom_lint test
