name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-lib:
    name: Lint lib folder
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Check dart format in lib
        run: dart format --set-exit-if-changed lib

      - name: Run dart analyze in lib
        run: dart analyze lib

  lint-test:
    name: Lint test folder
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Check dart format in test
        run: dart format --set-exit-if-changed test

      - name: Run dart analyze in test
        run: dart analyze test

      - name: Run custom_lint in test
        run: dart run custom_lint test
